Error: A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. This won't be patched up. This can happen if a SSR-ed Client Component used:
- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

https://react.dev/link/hydration-mismatch

  ...
    <ErrorBoundary errorComponent={undefined} errorStyles={undefined} errorScripts={undefined}>
      <LoadingBoundary loading={null}>
        <HTTPAccessFallbackBoundary notFound={[...]} forbidden={undefined} unauthorized={undefined}>
          <HTTPAccessFallbackErrorBoundary pathname="/" notFound={[...]} forbidden={undefined} unauthorized={undefined} ...>
            <RedirectBoundary>
              <RedirectErrorBoundary router={{...}}>
                <InnerLayoutRouter url="/" tree={[...]} cacheNode={{lazyData:null, ...}} segmentPath={[...]}>
                  <Home>
                    <main className="flex flex-...">
                      <HeroSection>
                        <section id="home" className="jsx-bd159e...">
                          <div>
                          <h1>
                          <p>
                          <p>
                          <LinkComponent href="#about" passHref={true}>
                            <a ref={function} onClick={function onClick} onMouseEnter={function onMouseEnter} ...>
                              <_c variant="outline" size="lg" className="rounded-fu..." aria-label="Scroll dow...">
                                <button
                                  className={"inline-flex items-center justify-center gap-2 whitespace-nowrap font-me..."}
                                  ref={null}
                                  aria-label="Scroll down to About section"
-                                 fdprocessedid="0h2dgo"
                                >
                          ...
                      <section>
                      <section>
                      <FocusAreasSection>
                      <ContactSection>
                        <section id="contact" className="py-20 md:p...">
                          <div className="max-w-3xl ...">
                            <SectionTitle>
                            <form onSubmit={function handleSubmit} className="mt-12 spac...">
                              <div className="grid grid-...">
                                <div className="space-y-2 ...">
                                  <_c>
                                  <_c id="name" name="name" type="text" placeholder="Your Name" required={true} ...>
                                    <input
                                      type="text"
                                      className="flex h-10 w-full rounded-md border border-input px-3 py-2 text-base r..."
                                      ref={null}
                                      id="name"
                                      name="name"
                                      placeholder="Your Name"
                                      required={true}
-                                     fdprocessedid="d8isp"
                                    >
                                <div className="space-y-2 ...">
                                  <_c>
                                  <_c id="email" name="email" type="email" placeholder="your.email..." required={true} ...>
                                    <input
                                      type="email"
                                      className="flex h-10 w-full rounded-md border border-input px-3 py-2 text-base r..."
                                      ref={null}
                                      id="email"
                                      name="email"
                                      placeholder="your.email@example.com"
                                      required={true}
-                                     fdprocessedid="to2quf"
                                    >
                              <div>
                              <_c type="submit" size="lg" className="w-full md:...">
                                <button
                                  className={"inline-flex items-center justify-center gap-2 whitespace-nowrap font-me..."}
                                  ref={null}
                                  type="submit"
-                                 fdprocessedid="jxztfn"
                                >
                            <div className="mt-16 flex...">
                              <SocialIcon href="https://gi..." icon={{...}} label="GitHub">
                                <LinkComponent href="https://gi..." target="_blank" rel="noopener n..." ...>
                                  <a target="_blank" rel="noopener n..." aria-label="GitHub" ref={function} ...>
                                    <_c variant="outline" size="icon" className="rounded-fu...">
                                      <button
                                        className={"inline-flex items-center justify-center gap-2 whitespace-nowrap t..."}
                                        ref={null}
-                                       fdprocessedid="ehxsz"
                                      >
                              <SocialIcon href="mailto:exa..." icon={{...}} label="Email">
                                <LinkComponent href="mailto:exa..." target="_blank" rel="noopener n..." ...>
                                  <a target="_blank" rel="noopener n..." aria-label="Email" ref={function} ...>
                                    <_c variant="outline" size="icon" className="rounded-fu...">
                                      <button
                                        className={"inline-flex items-center justify-center gap-2 whitespace-nowrap t..."}
                                        ref={null}
-                                       fdprocessedid="km4gqh"
                                      >
                              <SocialIcon href="https://it..." icon={{...}} label="Itch.io">
                                <LinkComponent href="https://it..." target="_blank" rel="noopener n..." ...>
                                  <a target="_blank" rel="noopener n..." aria-label="Itch.io" ref={function} ...>
                                    <_c variant="outline" size="icon" className="rounded-fu...">
                                      <button
                                        className={"inline-flex items-center justify-center gap-2 whitespace-nowrap t..."}
                                        ref={null}
-                                       fdprocessedid="fzywi9"
                                      >
                            ...
                  ...

    at createUnhandledError (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9382:25
    at runWithFiberInDEV (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:74)
    at emitPendingHydrationWarnings (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9381:13)
    at completeWork (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9455:102)
    at runWithFiberInDEV (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:131)
    at completeUnitOfWork (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10233:23)
    at performUnitOfWork (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10170:28)
    at workLoopConcurrentByScheduler (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10164:58)
    at renderRootConcurrent (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10146:71)
    at performWorkOnRoot (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9784:176)
    at performWorkOnRootViaSchedulerTask (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10796:9)
    at MessagePort.performWorkUntilDeadline (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:1952:64)
    at button (<anonymous>)
    at _c (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/src_components_d3dbc2e8._.js:46:214)
    at HeroSection (https://6000-idx-studio-1746453783622.cluster-zkm2jrwbnbd4awuedc2alqxrpk.cloudworkstations.dev/_next/static/chunks/src_components_d3dbc2e8._.js:151:229)
    at Home (rsc://React/Server/file:///home/user/studio/.next/server/chunks/ssr/_9554abec._.js?14:570:264) fix the error